//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Envelope {

    private Header headerField;

    private Body bodyField;

    private System.Xml.XmlElement[] anyField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    public Header Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }

    /// <remarks/>
    public Body Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Header {

    private HeaderInfoType headerInfoField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
    public HeaderInfoType HeaderInfo {
        get {
            return this.headerInfoField;
        }
        set {
            this.headerInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
[System.Xml.Serialization.XmlRootAttribute("HeaderInfo", Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1", IsNullable = false)]
public partial class HeaderInfoType {

    private int interfaceTypeIdField;

    private string businessPartnerIdField;

    private decimal schemaVersionField;

    private System.DateTime dateTimeField;

    private int controlTotalField;

    private bool controlTotalFieldSpecified;

    private int sequenceField;

    private bool sequenceFieldSpecified;

    private string contactNameField;

    private string contactEmailField;

    /// <remarks/>
    public int InterfaceTypeId {
        get {
            return this.interfaceTypeIdField;
        }
        set {
            this.interfaceTypeIdField = value;
        }
    }

    /// <remarks/>
    public string BusinessPartnerId {
        get {
            return this.businessPartnerIdField;
        }
        set {
            this.businessPartnerIdField = value;
        }
    }

    /// <remarks/>
    public decimal SchemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }

    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }

    /// <remarks/>
    public int ControlTotal {
        get {
            return this.controlTotalField;
        }
        set {
            this.controlTotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ControlTotalSpecified {
        get {
            return this.controlTotalFieldSpecified;
        }
        set {
            this.controlTotalFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int Sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SequenceSpecified {
        get {
            return this.sequenceFieldSpecified;
        }
        set {
            this.sequenceFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }

    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
public partial class detail {

    private System.Xml.XmlElement[] anyField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Body {
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Fault {

    private System.Xml.XmlQualifiedName faultcodeField;

    private string faultstringField;

    private string faultactorField;

    private detail detailField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.Xml.XmlQualifiedName faultcode {
        get {
            return this.faultcodeField;
        }
        set {
            this.faultcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string faultstring {
        get {
            return this.faultstringField;
        }
        set {
            this.faultstringField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string faultactor {
        get {
            return this.faultactorField;
        }
        set {
            this.faultactorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public detail detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
[System.Xml.Serialization.XmlRootAttribute("RetirementHealthEnrollment", Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1", IsNullable = false)]

public partial class RetirementHealthEnrollmentType{
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "schemaLocation", Namespace = "http://www.w3.org/2001/XMLSchema-instance")]
    public string schemaLocation = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1 RetirementHealthTransactionsV1.xsd";
    private TransactionType[] transactionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transaction", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransactionType[] Transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class TransactionType {

    private string transactionType1Field;

    private string uniqueTransactionIdField;

    private bool reapplyIndicatorField;

    private bool reapplyIndicatorFieldSpecified;

    private bool rescindIndicatorField;

    private bool rescindIndicatorFieldSpecified;

    private bool deletionIndicatorField;

    private bool deletionIndicatorFieldSpecified;

    private bool correctionIndicatorField;

    private bool correctionIndicatorFieldSpecified;

    private string rescindReasonField;

    private string rescindNotesField;

    private System.DateTime transactionEffectiveDateField;

    private bool transactionEffectiveDateFieldSpecified;

    private System.DateTime priorTransactionEffectiveDateField;

    private bool priorTransactionEffectiveDateFieldSpecified;

    private string newSSNField;

    private TransactionTypeDemographics demographicsField;

    private TransactionTypeAppointment appointmentField;

    private TransactionTypeRetirementEnrollment retirementEnrollmentField;

    private TransactionTypeHealthEnrollment healthEnrollmentField;

    private ErrorType[] errorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TransactionType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionType1 {
        get {
            return this.transactionType1Field;
        }
        set {
            this.transactionType1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UniqueTransactionId {
        get {
            return this.uniqueTransactionIdField;
        }
        set {
            this.uniqueTransactionIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ReapplyIndicator {
        get {
            return this.reapplyIndicatorField;
        }
        set {
            this.reapplyIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReapplyIndicatorSpecified {
        get {
            return this.reapplyIndicatorFieldSpecified;
        }
        set {
            this.reapplyIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RescindIndicator {
        get {
            return this.rescindIndicatorField;
        }
        set {
            this.rescindIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RescindIndicatorSpecified {
        get {
            return this.rescindIndicatorFieldSpecified;
        }
        set {
            this.rescindIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool DeletionIndicator {
        get {
            return this.deletionIndicatorField;
        }
        set {
            this.deletionIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeletionIndicatorSpecified {
        get {
            return this.deletionIndicatorFieldSpecified;
        }
        set {
            this.deletionIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool CorrectionIndicator {
        get {
            return this.correctionIndicatorField;
        }
        set {
            this.correctionIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CorrectionIndicatorSpecified {
        get {
            return this.correctionIndicatorFieldSpecified;
        }
        set {
            this.correctionIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RescindReason {
        get {
            return this.rescindReasonField;
        }
        set {
            this.rescindReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RescindNotes {
        get {
            return this.rescindNotesField;
        }
        set {
            this.rescindNotesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime TransactionEffectiveDate {
        get {
            return this.transactionEffectiveDateField;
        }
        set {
            this.transactionEffectiveDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransactionEffectiveDateSpecified {
        get {
            return this.transactionEffectiveDateFieldSpecified;
        }
        set {
            this.transactionEffectiveDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime PriorTransactionEffectiveDate {
        get {
            return this.priorTransactionEffectiveDateField;
        }
        set {
            this.priorTransactionEffectiveDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PriorTransactionEffectiveDateSpecified {
        get {
            return this.priorTransactionEffectiveDateFieldSpecified;
        }
        set {
            this.priorTransactionEffectiveDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NewSSN {
        get {
            return this.newSSNField;
        }
        set {
            this.newSSNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransactionTypeDemographics Demographics {
        get {
            return this.demographicsField;
        }
        set {
            this.demographicsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransactionTypeAppointment Appointment {
        get {
            return this.appointmentField;
        }
        set {
            this.appointmentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransactionTypeRetirementEnrollment RetirementEnrollment {
        get {
            return this.retirementEnrollmentField;
        }
        set {
            this.retirementEnrollmentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransactionTypeHealthEnrollment HealthEnrollment {
        get {
            return this.healthEnrollmentField;
        }
        set {
            this.healthEnrollmentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Error", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ErrorType[] Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class TransactionTypeDemographics {

    private PersonInfoType personInfoField;

    private bool useAddressForHealthField;

    private bool useAddressForHealthFieldSpecified;

    private AddressInfoType addressInfoField;

    private CommunicationInfoType communicationInfoField;

    /// <remarks/>
    public PersonInfoType PersonInfo {
        get {
            return this.personInfoField;
        }
        set {
            this.personInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool UseAddressForHealth {
        get {
            return this.useAddressForHealthField;
        }
        set {
            this.useAddressForHealthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UseAddressForHealthSpecified {
        get {
            return this.useAddressForHealthFieldSpecified;
        }
        set {
            this.useAddressForHealthFieldSpecified = value;
        }
    }

    /// <remarks/>
    public AddressInfoType AddressInfo {
        get {
            return this.addressInfoField;
        }
        set {
            this.addressInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CommunicationInfoType CommunicationInfo {
        get {
            return this.communicationInfoField;
        }
        set {
            this.communicationInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
[System.Xml.Serialization.XmlRootAttribute("PersonInfo", Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1", IsNullable = false)]
public partial class PersonInfoType {

    private IdentifierType personIdField;

    private string personIdTypeField;

    private string prefixField;

    private string firstNameField;

    private string middleNameField;

    private string lastNameField;

    private string suffixField;

    private System.DateTime birthDateField;

    private bool birthDateFieldSpecified;

    private string genderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IdentifierType PersonId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PersonIdType {
        get {
            return this.personIdTypeField;
        }
        set {
            this.personIdTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BirthDateSpecified {
        get {
            return this.birthDateFieldSpecified;
        }
        set {
            this.birthDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
public partial class IdentifierType {

    private string itemField;

    private ItemChoiceType itemElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CalPERSId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SSN", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1", IncludeInSchema = false)]
public enum ItemChoiceType {

    /// <remarks/>
    CalPERSId,

    /// <remarks/>
    SSN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
[System.Xml.Serialization.XmlRootAttribute("AddressInfo", Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1", IsNullable = false)]
public partial class AddressInfoType {

    private string addressTypeField;

    private string[] addressLineField;

    private string cityField;

    private string stateField;

    private string zipCode5Field;

    private string zipCode4Field;

    private string countryField;

    private string provinceField;

    private string postalCodeField;

    /// <remarks/>
    public string AddressType {
        get {
            return this.addressTypeField;
        }
        set {
            this.addressTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddressLine")]
    public string[] AddressLine {
        get {
            return this.addressLineField;
        }
        set {
            this.addressLineField = value;
        }
    }

    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }

    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }

    /// <remarks/>
    public string ZipCode5 {
        get {
            return this.zipCode5Field;
        }
        set {
            this.zipCode5Field = value;
        }
    }

    /// <remarks/>
    public string ZipCode4 {
        get {
            return this.zipCode4Field;
        }
        set {
            this.zipCode4Field = value;
        }
    }

    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }

    /// <remarks/>
    public string Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }

    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class CommunicationInfoType {

    private PhoneInfoType phoneField;

    private string emailField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PhoneInfoType Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
public partial class PhoneInfoType {

    private string phoneTypeField;

    private string itemField;

    private ItemChoiceType1 itemElementNameField;

    private string extensionField;

    /// <remarks/>
    public string PhoneType {
        get {
            return this.phoneTypeField;
        }
        set {
            this.phoneTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InternationalPhone", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("USPhone", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }

    /// <remarks/>
    public string Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1", IncludeInSchema = false)]
public enum ItemChoiceType1 {

    /// <remarks/>
    InternationalPhone,

    /// <remarks/>
    USPhone,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class TransactionTypeAppointment {

    private EmployerInfoType employerInfoField;

    private EmploymentInfoType employmentInfoField;

    private JobPositionInfoType jobPositionInfoField;

    private ReciprocityInfoType reciprocityInfoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EmployerInfoType EmployerInfo {
        get {
            return this.employerInfoField;
        }
        set {
            this.employerInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EmploymentInfoType EmploymentInfo {
        get {
            return this.employmentInfoField;
        }
        set {
            this.employmentInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public JobPositionInfoType JobPositionInfo {
        get {
            return this.jobPositionInfoField;
        }
        set {
            this.jobPositionInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReciprocityInfoType ReciprocityInfo {
        get {
            return this.reciprocityInfoField;
        }
        set {
            this.reciprocityInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class EmployerInfoType {

    private string employerCalPERSIdField;

    private int agencyCodeField;

    private bool agencyCodeFieldSpecified;

    private string countyField;

    private string divisionCalPERSIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmployerCalPERSId {
        get {
            return this.employerCalPERSIdField;
        }
        set {
            this.employerCalPERSIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int AgencyCode {
        get {
            return this.agencyCodeField;
        }
        set {
            this.agencyCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AgencyCodeSpecified {
        get {
            return this.agencyCodeFieldSpecified;
        }
        set {
            this.agencyCodeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DivisionCalPERSId {
        get {
            return this.divisionCalPERSIdField;
        }
        set {
            this.divisionCalPERSIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class EmploymentInfoType {

    private System.DateTime originalHireDateField;

    private bool originalHireDateFieldSpecified;

    private string leaveOfAbsenceTypeField;

    private string permSepReasonField;

    private bool tempApptField;

    private bool tempApptFieldSpecified;

    private System.DateTime tempApptSepDateField;

    private bool tempApptSepDateFieldSpecified;

    private string workCalendarField;

    private string cBUField;

    private string exemptAuthorityField;

    private bool retiredAnnuitantField;

    private bool retiredAnnuitantFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime OriginalHireDate {
        get {
            return this.originalHireDateField;
        }
        set {
            this.originalHireDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OriginalHireDateSpecified {
        get {
            return this.originalHireDateFieldSpecified;
        }
        set {
            this.originalHireDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LeaveOfAbsenceType {
        get {
            return this.leaveOfAbsenceTypeField;
        }
        set {
            this.leaveOfAbsenceTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PermSepReason {
        get {
            return this.permSepReasonField;
        }
        set {
            this.permSepReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool TempAppt {
        get {
            return this.tempApptField;
        }
        set {
            this.tempApptField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TempApptSpecified {
        get {
            return this.tempApptFieldSpecified;
        }
        set {
            this.tempApptFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime TempApptSepDate {
        get {
            return this.tempApptSepDateField;
        }
        set {
            this.tempApptSepDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TempApptSepDateSpecified {
        get {
            return this.tempApptSepDateFieldSpecified;
        }
        set {
            this.tempApptSepDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkCalendar {
        get {
            return this.workCalendarField;
        }
        set {
            this.workCalendarField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CBU {
        get {
            return this.cBUField;
        }
        set {
            this.cBUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExemptAuthority {
        get {
            return this.exemptAuthorityField;
        }
        set {
            this.exemptAuthorityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RetiredAnnuitant {
        get {
            return this.retiredAnnuitantField;
        }
        set {
            this.retiredAnnuitantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RetiredAnnuitantSpecified {
        get {
            return this.retiredAnnuitantFieldSpecified;
        }
        set {
            this.retiredAnnuitantFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class JobPositionInfoType {

    private JobPositionInfoTypePositionCode positionCodeField;

    private string appointmentIdField;

    private string externalPositionNumberField;

    private string appointmentSequenceNumberField;

    private string retirementSystemField;

    private string memberCategoryField;

    private string tierField;

    private string courtLevelField;

    private string assignmentTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public JobPositionInfoTypePositionCode PositionCode {
        get {
            return this.positionCodeField;
        }
        set {
            this.positionCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppointmentId {
        get {
            return this.appointmentIdField;
        }
        set {
            this.appointmentIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExternalPositionNumber {
        get {
            return this.externalPositionNumberField;
        }
        set {
            this.externalPositionNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppointmentSequenceNumber {
        get {
            return this.appointmentSequenceNumberField;
        }
        set {
            this.appointmentSequenceNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RetirementSystem {
        get {
            return this.retirementSystemField;
        }
        set {
            this.retirementSystemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MemberCategory {
        get {
            return this.memberCategoryField;
        }
        set {
            this.memberCategoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CourtLevel {
        get {
            return this.courtLevelField;
        }
        set {
            this.courtLevelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AssignmentType {
        get {
            return this.assignmentTypeField;
        }
        set {
            this.assignmentTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class JobPositionInfoTypePositionCode {

    private string sourceField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class ReciprocityInfoType {

    private bool reciprocalAgencyIndicatorField;

    private bool reciprocalAgencyIndicatorFieldSpecified;

    private string reciprocalAgencyCalPERSIDField;

    private System.DateTime reciprocalMembershipDateField;

    private bool reciprocalMembershipDateFieldSpecified;

    private System.DateTime reciprocalPermanentSeparationDateField;

    private bool reciprocalPermanentSeparationDateFieldSpecified;

    private bool retiredReciprocalMemberIndicatorField;

    private bool retiredReciprocalMemberIndicatorFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ReciprocalAgencyIndicator {
        get {
            return this.reciprocalAgencyIndicatorField;
        }
        set {
            this.reciprocalAgencyIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReciprocalAgencyIndicatorSpecified {
        get {
            return this.reciprocalAgencyIndicatorFieldSpecified;
        }
        set {
            this.reciprocalAgencyIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReciprocalAgencyCalPERSID {
        get {
            return this.reciprocalAgencyCalPERSIDField;
        }
        set {
            this.reciprocalAgencyCalPERSIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime ReciprocalMembershipDate {
        get {
            return this.reciprocalMembershipDateField;
        }
        set {
            this.reciprocalMembershipDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReciprocalMembershipDateSpecified {
        get {
            return this.reciprocalMembershipDateFieldSpecified;
        }
        set {
            this.reciprocalMembershipDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime ReciprocalPermanentSeparationDate {
        get {
            return this.reciprocalPermanentSeparationDateField;
        }
        set {
            this.reciprocalPermanentSeparationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReciprocalPermanentSeparationDateSpecified {
        get {
            return this.reciprocalPermanentSeparationDateFieldSpecified;
        }
        set {
            this.reciprocalPermanentSeparationDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RetiredReciprocalMemberIndicator {
        get {
            return this.retiredReciprocalMemberIndicatorField;
        }
        set {
            this.retiredReciprocalMemberIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RetiredReciprocalMemberIndicatorSpecified {
        get {
            return this.retiredReciprocalMemberIndicatorFieldSpecified;
        }
        set {
            this.retiredReciprocalMemberIndicatorFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class TransactionTypeRetirementEnrollment {

    private string programField;

    private decimal unusedSickLeaveField;

    private bool unusedSickLeaveFieldSpecified;

    private decimal unusedEducationLeaveField;

    private bool unusedEducationLeaveFieldSpecified;

    private bool pLPParticipantField;

    private bool pLPParticipantFieldSpecified;

    private decimal pLPRatesField;

    private bool pLPRatesFieldSpecified;

    private bool coveredBySSAField;

    private bool coveredBySSAFieldSpecified;

    private bool coveredBy59SurvivorField;

    private bool coveredBy59SurvivorFieldSpecified;

    private string optionalMemberPositionField;

    private System.DateTime optionalMemberDateOfEntryField;

    private bool optionalMemberDateOfEntryFieldSpecified;

    private bool sTRSElectingPERSField;

    private bool sTRSElectingPERSFieldSpecified;

    private bool localARPField;

    private bool localARPFieldSpecified;

    private bool stateARPField;

    private bool stateARPFieldSpecified;

    private System.DateTime stateARPDateOfEntryField;

    private bool stateARPDateOfEntryFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Program {
        get {
            return this.programField;
        }
        set {
            this.programField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal UnusedSickLeave {
        get {
            return this.unusedSickLeaveField;
        }
        set {
            this.unusedSickLeaveField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnusedSickLeaveSpecified {
        get {
            return this.unusedSickLeaveFieldSpecified;
        }
        set {
            this.unusedSickLeaveFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal UnusedEducationLeave {
        get {
            return this.unusedEducationLeaveField;
        }
        set {
            this.unusedEducationLeaveField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnusedEducationLeaveSpecified {
        get {
            return this.unusedEducationLeaveFieldSpecified;
        }
        set {
            this.unusedEducationLeaveFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool PLPParticipant {
        get {
            return this.pLPParticipantField;
        }
        set {
            this.pLPParticipantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PLPParticipantSpecified {
        get {
            return this.pLPParticipantFieldSpecified;
        }
        set {
            this.pLPParticipantFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PLPRates {
        get {
            return this.pLPRatesField;
        }
        set {
            this.pLPRatesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PLPRatesSpecified {
        get {
            return this.pLPRatesFieldSpecified;
        }
        set {
            this.pLPRatesFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool CoveredBySSA {
        get {
            return this.coveredBySSAField;
        }
        set {
            this.coveredBySSAField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CoveredBySSASpecified {
        get {
            return this.coveredBySSAFieldSpecified;
        }
        set {
            this.coveredBySSAFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool CoveredBy59Survivor {
        get {
            return this.coveredBy59SurvivorField;
        }
        set {
            this.coveredBy59SurvivorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CoveredBy59SurvivorSpecified {
        get {
            return this.coveredBy59SurvivorFieldSpecified;
        }
        set {
            this.coveredBy59SurvivorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OptionalMemberPosition {
        get {
            return this.optionalMemberPositionField;
        }
        set {
            this.optionalMemberPositionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime OptionalMemberDateOfEntry {
        get {
            return this.optionalMemberDateOfEntryField;
        }
        set {
            this.optionalMemberDateOfEntryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OptionalMemberDateOfEntrySpecified {
        get {
            return this.optionalMemberDateOfEntryFieldSpecified;
        }
        set {
            this.optionalMemberDateOfEntryFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool STRSElectingPERS {
        get {
            return this.sTRSElectingPERSField;
        }
        set {
            this.sTRSElectingPERSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool STRSElectingPERSSpecified {
        get {
            return this.sTRSElectingPERSFieldSpecified;
        }
        set {
            this.sTRSElectingPERSFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool LocalARP {
        get {
            return this.localARPField;
        }
        set {
            this.localARPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LocalARPSpecified {
        get {
            return this.localARPFieldSpecified;
        }
        set {
            this.localARPFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool StateARP {
        get {
            return this.stateARPField;
        }
        set {
            this.stateARPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StateARPSpecified {
        get {
            return this.stateARPFieldSpecified;
        }
        set {
            this.stateARPFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime StateARPDateOfEntry {
        get {
            return this.stateARPDateOfEntryField;
        }
        set {
            this.stateARPDateOfEntryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StateARPDateOfEntrySpecified {
        get {
            return this.stateARPDateOfEntryFieldSpecified;
        }
        set {
            this.stateARPDateOfEntryFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class TransactionTypeHealthEnrollment {

    private string healthEventReasonField;

    private System.DateTime eventDateField;

    private bool eventDateFieldSpecified;

    private System.DateTime receivedDateField;

    private bool receivedDateFieldSpecified;

    private string medicalGroupField;

    private string affiliatedAssociationField;

    private System.DateTime permSepDateField;

    private bool permSepDateFieldSpecified;

    private System.DateTime retirementDateField;

    private bool retirementDateFieldSpecified;

    private SubscriberInfoType subscriberInfoField;

    private PersonInfoType qualifyingPersonInfoField;

    private DependentInfoType[] dependentInfoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HealthEventReason {
        get {
            return this.healthEventReasonField;
        }
        set {
            this.healthEventReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime EventDate {
        get {
            return this.eventDateField;
        }
        set {
            this.eventDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EventDateSpecified {
        get {
            return this.eventDateFieldSpecified;
        }
        set {
            this.eventDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime ReceivedDate {
        get {
            return this.receivedDateField;
        }
        set {
            this.receivedDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceivedDateSpecified {
        get {
            return this.receivedDateFieldSpecified;
        }
        set {
            this.receivedDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MedicalGroup {
        get {
            return this.medicalGroupField;
        }
        set {
            this.medicalGroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AffiliatedAssociation {
        get {
            return this.affiliatedAssociationField;
        }
        set {
            this.affiliatedAssociationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime PermSepDate {
        get {
            return this.permSepDateField;
        }
        set {
            this.permSepDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PermSepDateSpecified {
        get {
            return this.permSepDateFieldSpecified;
        }
        set {
            this.permSepDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime RetirementDate {
        get {
            return this.retirementDateField;
        }
        set {
            this.retirementDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RetirementDateSpecified {
        get {
            return this.retirementDateFieldSpecified;
        }
        set {
            this.retirementDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SubscriberInfoType SubscriberInfo {
        get {
            return this.subscriberInfoField;
        }
        set {
            this.subscriberInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PersonInfoType QualifyingPersonInfo {
        get {
            return this.qualifyingPersonInfoField;
        }
        set {
            this.qualifyingPersonInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DependentInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DependentInfoType[] DependentInfo {
        get {
            return this.dependentInfoField;
        }
        set {
            this.dependentInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class SubscriberInfoType {

    private bool applyChangeToMedicalPlanField;

    private bool applyChangeToDentalPlanField;

    private bool applyChangeToVisionPlanField;

    private bool changeToMedicalPartyRateField;

    private bool changeToMedicalPartyRateFieldSpecified;

    private bool changeToDentalPartyRateField;

    private bool changeToDentalPartyRateFieldSpecified;

    private bool changeToVisionPartyRateField;

    private bool changeToVisionPartyRateFieldSpecified;

    private bool domesticPartnershipIndicatorField;

    private bool domesticPartnershipIndicatorFieldSpecified;

    private System.DateTime originalCOBRAStartDateField;

    private bool originalCOBRAStartDateFieldSpecified;

    private string cOBRAEligibilityBasisField;

    private bool fERPStatusField;

    private bool fERPStatusFieldSpecified;

    private System.DateTime fERPStatusStartDateField;

    private bool fERPStatusStartDateFieldSpecified;

    private System.DateTime fERPStatusEndDateField;

    private bool fERPStatusEndDateFieldSpecified;

    private string healthEligibilityZipCodeTypeField;

    private string healthEligibilityZipCodeField;

    private string healthEligibilityCountyField;

    private string medicalPlanSelectionField;

    private string medicalPartyRateField;

    private string dentalPlanSelectionField;

    private string dentalPartyRateField;

    private string visionPlanSelectionField;

    private string visionPartyRateField;

    private string calPERSIdField;

    private System.DateTime cOBRAEndDateField;

    private bool cOBRAEndDateFieldSpecified;

    private string medicalEligibilityBasisField;

    private string dentalEligibilityBasisField;

    private string visionEligibilityBasisField;

    private bool changeMedicalPartyRateField;

    private bool changeMedicalPartyRateFieldSpecified;

    private bool changeDentalPartyRateField;

    private bool changeDentalPartyRateFieldSpecified;

    private bool changeVisionPartyRateField;

    private bool changeVisionPartyRateFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ApplyChangeToMedicalPlan {
        get {
            return this.applyChangeToMedicalPlanField;
        }
        set {
            this.applyChangeToMedicalPlanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ApplyChangeToDentalPlan {
        get {
            return this.applyChangeToDentalPlanField;
        }
        set {
            this.applyChangeToDentalPlanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ApplyChangeToVisionPlan {
        get {
            return this.applyChangeToVisionPlanField;
        }
        set {
            this.applyChangeToVisionPlanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ChangeToMedicalPartyRate {
        get {
            return this.changeToMedicalPartyRateField;
        }
        set {
            this.changeToMedicalPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeToMedicalPartyRateSpecified {
        get {
            return this.changeToMedicalPartyRateFieldSpecified;
        }
        set {
            this.changeToMedicalPartyRateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ChangeToDentalPartyRate {
        get {
            return this.changeToDentalPartyRateField;
        }
        set {
            this.changeToDentalPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeToDentalPartyRateSpecified {
        get {
            return this.changeToDentalPartyRateFieldSpecified;
        }
        set {
            this.changeToDentalPartyRateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ChangeToVisionPartyRate {
        get {
            return this.changeToVisionPartyRateField;
        }
        set {
            this.changeToVisionPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeToVisionPartyRateSpecified {
        get {
            return this.changeToVisionPartyRateFieldSpecified;
        }
        set {
            this.changeToVisionPartyRateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool DomesticPartnershipIndicator {
        get {
            return this.domesticPartnershipIndicatorField;
        }
        set {
            this.domesticPartnershipIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DomesticPartnershipIndicatorSpecified {
        get {
            return this.domesticPartnershipIndicatorFieldSpecified;
        }
        set {
            this.domesticPartnershipIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime OriginalCOBRAStartDate {
        get {
            return this.originalCOBRAStartDateField;
        }
        set {
            this.originalCOBRAStartDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OriginalCOBRAStartDateSpecified {
        get {
            return this.originalCOBRAStartDateFieldSpecified;
        }
        set {
            this.originalCOBRAStartDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COBRAEligibilityBasis {
        get {
            return this.cOBRAEligibilityBasisField;
        }
        set {
            this.cOBRAEligibilityBasisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool FERPStatus {
        get {
            return this.fERPStatusField;
        }
        set {
            this.fERPStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FERPStatusSpecified {
        get {
            return this.fERPStatusFieldSpecified;
        }
        set {
            this.fERPStatusFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime FERPStatusStartDate {
        get {
            return this.fERPStatusStartDateField;
        }
        set {
            this.fERPStatusStartDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FERPStatusStartDateSpecified {
        get {
            return this.fERPStatusStartDateFieldSpecified;
        }
        set {
            this.fERPStatusStartDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime FERPStatusEndDate {
        get {
            return this.fERPStatusEndDateField;
        }
        set {
            this.fERPStatusEndDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FERPStatusEndDateSpecified {
        get {
            return this.fERPStatusEndDateFieldSpecified;
        }
        set {
            this.fERPStatusEndDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HealthEligibilityZipCodeType {
        get {
            return this.healthEligibilityZipCodeTypeField;
        }
        set {
            this.healthEligibilityZipCodeTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HealthEligibilityZipCode {
        get {
            return this.healthEligibilityZipCodeField;
        }
        set {
            this.healthEligibilityZipCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HealthEligibilityCounty {
        get {
            return this.healthEligibilityCountyField;
        }
        set {
            this.healthEligibilityCountyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MedicalPlanSelection {
        get {
            return this.medicalPlanSelectionField;
        }
        set {
            this.medicalPlanSelectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MedicalPartyRate {
        get {
            return this.medicalPartyRateField;
        }
        set {
            this.medicalPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DentalPlanSelection {
        get {
            return this.dentalPlanSelectionField;
        }
        set {
            this.dentalPlanSelectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DentalPartyRate {
        get {
            return this.dentalPartyRateField;
        }
        set {
            this.dentalPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VisionPlanSelection {
        get {
            return this.visionPlanSelectionField;
        }
        set {
            this.visionPlanSelectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VisionPartyRate {
        get {
            return this.visionPartyRateField;
        }
        set {
            this.visionPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CalPERSId {
        get {
            return this.calPERSIdField;
        }
        set {
            this.calPERSIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime COBRAEndDate {
        get {
            return this.cOBRAEndDateField;
        }
        set {
            this.cOBRAEndDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool COBRAEndDateSpecified {
        get {
            return this.cOBRAEndDateFieldSpecified;
        }
        set {
            this.cOBRAEndDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MedicalEligibilityBasis {
        get {
            return this.medicalEligibilityBasisField;
        }
        set {
            this.medicalEligibilityBasisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DentalEligibilityBasis {
        get {
            return this.dentalEligibilityBasisField;
        }
        set {
            this.dentalEligibilityBasisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VisionEligibilityBasis {
        get {
            return this.visionEligibilityBasisField;
        }
        set {
            this.visionEligibilityBasisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ChangeMedicalPartyRate {
        get {
            return this.changeMedicalPartyRateField;
        }
        set {
            this.changeMedicalPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeMedicalPartyRateSpecified {
        get {
            return this.changeMedicalPartyRateFieldSpecified;
        }
        set {
            this.changeMedicalPartyRateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ChangeDentalPartyRate {
        get {
            return this.changeDentalPartyRateField;
        }
        set {
            this.changeDentalPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeDentalPartyRateSpecified {
        get {
            return this.changeDentalPartyRateFieldSpecified;
        }
        set {
            this.changeDentalPartyRateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ChangeVisionPartyRate {
        get {
            return this.changeVisionPartyRateField;
        }
        set {
            this.changeVisionPartyRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChangeVisionPartyRateSpecified {
        get {
            return this.changeVisionPartyRateFieldSpecified;
        }
        set {
            this.changeVisionPartyRateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
public partial class DependentInfoType {

    private DependentPersonInfoType dependentPersonInfoField;

    private string relationshipField;

    private System.DateTime dateOfPartnershipField;

    private bool dateOfPartnershipFieldSpecified;

    private bool addressSameAsPrimarySubscriberField;

    private bool addressSameAsPrimarySubscriberFieldSpecified;

    private AddressInfoType addressInfoField;

    private string dependentTypeField;

    private bool disabilityIndicatorField;

    private bool disabilityIndicatorFieldSpecified;

    private bool applyToMedicalField;

    private bool applyToMedicalFieldSpecified;

    private bool applyToDentalField;

    private bool applyToDentalFieldSpecified;

    private bool applyToVisionField;

    private bool applyToVisionFieldSpecified;

    private bool disabilityConfirmIndicatorField;

    private bool disabilityConfirmIndicatorFieldSpecified;

    private bool economicallyConfirmIndicatorField;

    private bool economicallyConfirmIndicatorFieldSpecified;

    private System.DateTime dependentAcquiredDateField;

    private bool dependentAcquiredDateFieldSpecified;

    private string calPERSIdField;

    private string recertificationReasonField;

    private bool recertificationConfirmationIndicatorField;

    private bool recertificationConfirmationIndicatorFieldSpecified;

    /// <remarks/>
    public DependentPersonInfoType DependentPersonInfo {
        get {
            return this.dependentPersonInfoField;
        }
        set {
            this.dependentPersonInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Relationship {
        get {
            return this.relationshipField;
        }
        set {
            this.relationshipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime DateOfPartnership {
        get {
            return this.dateOfPartnershipField;
        }
        set {
            this.dateOfPartnershipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateOfPartnershipSpecified {
        get {
            return this.dateOfPartnershipFieldSpecified;
        }
        set {
            this.dateOfPartnershipFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool AddressSameAsPrimarySubscriber {
        get {
            return this.addressSameAsPrimarySubscriberField;
        }
        set {
            this.addressSameAsPrimarySubscriberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddressSameAsPrimarySubscriberSpecified {
        get {
            return this.addressSameAsPrimarySubscriberFieldSpecified;
        }
        set {
            this.addressSameAsPrimarySubscriberFieldSpecified = value;
        }
    }

    /// <remarks/>
    public AddressInfoType AddressInfo {
        get {
            return this.addressInfoField;
        }
        set {
            this.addressInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DependentType {
        get {
            return this.dependentTypeField;
        }
        set {
            this.dependentTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool DisabilityIndicator {
        get {
            return this.disabilityIndicatorField;
        }
        set {
            this.disabilityIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DisabilityIndicatorSpecified {
        get {
            return this.disabilityIndicatorFieldSpecified;
        }
        set {
            this.disabilityIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ApplyToMedical {
        get {
            return this.applyToMedicalField;
        }
        set {
            this.applyToMedicalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ApplyToMedicalSpecified {
        get {
            return this.applyToMedicalFieldSpecified;
        }
        set {
            this.applyToMedicalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ApplyToDental {
        get {
            return this.applyToDentalField;
        }
        set {
            this.applyToDentalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ApplyToDentalSpecified {
        get {
            return this.applyToDentalFieldSpecified;
        }
        set {
            this.applyToDentalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ApplyToVision {
        get {
            return this.applyToVisionField;
        }
        set {
            this.applyToVisionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ApplyToVisionSpecified {
        get {
            return this.applyToVisionFieldSpecified;
        }
        set {
            this.applyToVisionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool DisabilityConfirmIndicator {
        get {
            return this.disabilityConfirmIndicatorField;
        }
        set {
            this.disabilityConfirmIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DisabilityConfirmIndicatorSpecified {
        get {
            return this.disabilityConfirmIndicatorFieldSpecified;
        }
        set {
            this.disabilityConfirmIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool EconomicallyConfirmIndicator {
        get {
            return this.economicallyConfirmIndicatorField;
        }
        set {
            this.economicallyConfirmIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EconomicallyConfirmIndicatorSpecified {
        get {
            return this.economicallyConfirmIndicatorFieldSpecified;
        }
        set {
            this.economicallyConfirmIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime DependentAcquiredDate {
        get {
            return this.dependentAcquiredDateField;
        }
        set {
            this.dependentAcquiredDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DependentAcquiredDateSpecified {
        get {
            return this.dependentAcquiredDateFieldSpecified;
        }
        set {
            this.dependentAcquiredDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CalPERSId {
        get {
            return this.calPERSIdField;
        }
        set {
            this.calPERSIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecertificationReason {
        get {
            return this.recertificationReasonField;
        }
        set {
            this.recertificationReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RecertificationConfirmationIndicator {
        get {
            return this.recertificationConfirmationIndicatorField;
        }
        set {
            this.recertificationConfirmationIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecertificationConfirmationIndicatorSpecified {
        get {
            return this.recertificationConfirmationIndicatorFieldSpecified;
        }
        set {
            this.recertificationConfirmationIndicatorFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
[System.Xml.Serialization.XmlRootAttribute("DependentPersonInfo", Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1", IsNullable = false)]
public partial class DependentPersonInfoType {

    private IdentifierType personIdField;

    private string personIdTypeField;

    private string prefixField;

    private string firstNameField;

    private string middleNameField;

    private string lastNameField;

    private string suffixField;

    private System.DateTime birthDateField;

    private bool birthDateFieldSpecified;

    private string genderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IdentifierType PersonId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PersonIdType {
        get {
            return this.personIdTypeField;
        }
        set {
            this.personIdTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BirthDateSpecified {
        get {
            return this.birthDateFieldSpecified;
        }
        set {
            this.birthDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
public partial class ErrorType {

    private string errorCodeField;

    private string errorFieldField;

    private ErrorTypeErrorSeverity errorSeverityField;

    private bool errorSeverityFieldSpecified;

    private string errorMessageField;

    /// <remarks/>
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }

    /// <remarks/>
    public string ErrorField {
        get {
            return this.errorFieldField;
        }
        set {
            this.errorFieldField = value;
        }
    }

    /// <remarks/>
    public ErrorTypeErrorSeverity ErrorSeverity {
        get {
            return this.errorSeverityField;
        }
        set {
            this.errorSeverityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ErrorSeveritySpecified {
        get {
            return this.errorSeverityFieldSpecified;
        }
        set {
            this.errorSeverityFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://calpers.ca.gov/PSR/CommonUtilitiesV1")]
public enum ErrorTypeErrorSeverity {

    /// <remarks/>
    Error,

    /// <remarks/>
    Exception,

    /// <remarks/>
    Confirmation,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1")]
[System.Xml.Serialization.XmlRootAttribute("EnrollmentAcknowledgment", Namespace = "http://calpers.ca.gov/PSR/RetirementHealthTransactionsV1", IsNullable = false)]
public partial class EnrollmentAcknowledgmentType {

    private string statusField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}
